# Generated by Django 2.2 on 2019-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
