# Generated by Django 2.2 on 2019-04-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.CharField(max_length=200)),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
