# Generated by Django 2.2 on 2019-04-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
